version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-packages-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: install packages
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-packages-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn test
  staging:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-packages-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: yarn build
          command: yarn build
      - run:
          name: surge
          command: npx surge --project build/ --philcicd-staging.surge.sh

workflows:
  orb-free-workflow:
    jobs:
      - test
      #- staging
