version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  test:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-packages-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: install packages
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-packages-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn test
  staging:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-packages-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: yarn build
          command: yarn build
      - run:
          name: surge
          command: npx surge build/ https://philcicd-staging.surge.sh
  uitest:
    docker:
      - image: cimg/node:14.15.4-browsers
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-packages-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: ui test
          command: yarn e2e
  perftest:
    docker:
      - image: cimg/node:14.15.4-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-packages-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: performance test
          command: yarn performance
  production_deploy:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-packages-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: install
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: yarn build
          command: yarn build
      - run:
          name: deploy to production
          command: npx surge build/ https://philcicd.surge.sh

workflows:
  orb-free-workflow:
    jobs:
      - test
      - staging:
          requires:
            - test
      - uitest:
          requires:
            - staging
      - perftest:
          requires:
            - staging
      - production_deploy:
          type: approval
          requires:
            - perftest
            - uitest
